# Generated by Django 4.2 on 2024-02-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_product_price_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="ammount",
            new_name="amount",
        ),
    ]
