# Generated by Django 4.2 on 2024-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_ammount_price_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="date created"),
        ),
    ]
