# Generated by Django 4.2 on 2024-02-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peyment", "0002_remove_order_product_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
