# Generated by Django 4.2 on 2024-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peyment", "0003_remove_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
