# Generated by Django 4.2 on 2024-02-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peyment", "0004_order_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("checkout", "checkout"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
