# Generated by Django 4.2 on 2024-02-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="image",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
    ]
