# Generated by Django 4.2 on 2024-02-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_is_active_alter_comment_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
    ]
