# Generated by Django 4.2 on 2024-02-18 16:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
