# Generated by Django 4.2 on 2024-02-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_image_post_alter_image_description_alter_image_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostImage",
        ),
    ]
